version: "3.2"

# ---- Database
services:
  db:
    image: couchdb:latest
    ports:
      - 5986:5986
      - 5984:5984
    expose:
      - 5986
      - 5984
    volumes:
      - couch-data:/opt/couchdb/data
    restart: always

# ---- Django
  djangobackend:
    build: ./djangobackend
    volumes:
      - ./djangobackend/:/app/django
    ports:
      - 8000:8000
    expose:
      - 8000
    stdin_open: true
    restart: always
    tty: true
    command: python3 manage.py runserver 0.0.0.0:8000
    depends_on: 
      - db
    entrypoint: /entrypoint.sh
    links:
      - db

# ---- ReactJS
  reactfrontend:
    build: ./reactfrontend
    volumes:
      - ./reactfrontend:/app/reactfrontend
      - node-modules:/app/reactfrontend/node_modules
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
    links: 
      - db
      - djangobackend
    depends_on:
      - djangobackend
    command: npm start

# ---- Volumes
volumes:
  couch-data:
  node-modules:
