esphome:
  name: perennial_1
  platform: ESP32
  board: nodemcu-32s

wifi:
  networks:
  - ssid: !secret network_ssid
    password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Perennial 1 Fallback Hotspot"
    password: "eQFxPdt1HtJl"

captive_portal:

# web_server:
#   port: 80

mqtt:
  broker: !secret mqtt_host
  # username: !secret mqtt_user
  # password: !secret mqtt_psswd
  client_id: !secret device_id

  birth_message:
    topic: perennial/0d2186ea38e106dd06b16f95ee011150/availability
    payload: online
  will_message:
    topic: perennial/0d2186ea38e106dd06b16f95ee011150/availability
    payload: offline
    
  on_message:
    topic: perennial/0d2186ea38e106dd06b16f95ee011150/pump
    then: 
      - switch.turn_off: pump
      - delay: 2s
      - switch.turn_on: pump
      - mqtt.publish:
          topic: perennial/0d2186ea38e106dd06b16f95ee011150/pumpstatus
          payload: "Ran pump for 2 seconds!"

# Enable logging
logger:

ota:

sensor:
  - platform: adc
    pin: A0
    name: "Moisture"
    update_interval: 60s
    attenuation: 11db
    state_topic: perennial/0d2186ea38e106dd06b16f95ee011150/moisture
    unit_of_measurement: "%"
    filters:
      - lambda: |-
          if (x > 3.3) {
            return 0;
          } else if (x < 1.7) {
            return 100;
          } else {
            return (3.3-x) / (3.3-1.7) * 100.0;
          }
  - platform: adc
    pin: A3
    name: "Reservoir"
    update_interval: 60s
    attenuation: 11db
    state_topic: perennial/0d2186ea38e106dd06b16f95ee011150/reservoir
    unit_of_measurement: "%"
    filters:
      - lambda: |-
          if (x > 3.3) {
            return 0;
          } else if (x < 1.7) {
            return 100;
          } else {
            return (3.3-x) / (3.3-1.7) * 100.0;
          }
          
switch:
  - platform: gpio
    name: "pump"
    pin: 
      number: GPIO23
      inverted: no
    id: pump