esphome:
  name: perennial_1
  platform: ESP32
  board: nodemcu-32s

wifi:
  networks:
  - ssid: "GOTTFEM"
    password: "password1"
  - ssid: "Frontier5696"
    password: "5919390335"
  - ssid: "Tuyet1"
    password: "apple123"
  - ssid: "NETGEAR71"
    password: "largebox284"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Perennial 1 Fallback Hotspot"
    password: "eQFxPdt1HtJl"

captive_portal:

web_server:
  port: 80
  
mqtt:
  broker: 'thslion.xyz'
  username: perennial
  password: projectperennial
  client_id: perennial_1
  
  birth_message:
    topic: perennial/availability
    payload: online
  will_message:
    topic: perennial/availability
    payload: offline

# Enable logging
logger:

ota:

sensor:
  - platform: adc
    pin: A0
    name: "Moisture"
    update_interval: 10s
    attenuation: 11db
    state_topic: perennial/moisture